### ISSUE TITLE
Is is possible to style or set handler to InViewMonitor?

### ISSUE THREAD

**Issue by MarcMagnin** [snipsco/react-inview-monitor#10]
Heya,
Thanks for that lib! I'd like to use it but it seems that I can't style it's div and it cause some issues on my current layout, any reason for that?

Many thanks!

**Comment by pocketjoso** [comment]
Hi,
you can repeat your class in the following two props if you need to:
```js
classNameNotInView='myClass'
classNameInView='myClass'
```
and then style it that way. Does that help you?

**Comment by MarcMagnin** [comment]
Absolutely! Thanks!
