### ISSUE TITLE
onInView delay?

### ISSUE THREAD

**Issue by MarcMagnin** [snipsco/react-inview-monitor#11]
Hi, thanks for this lib!

It seems that when my components are mounted on the page and in the view, the onInView event is raised 1-2 seconds after the component got rendered. Any idea why this could happen? 

Many thanks

**Comment by pocketjoso** [comment]
Hi again. So.. first of all if you element was in view when it mounted, it should have triggered the `onInView` straight away... was the element visible, with a non-zero height?

Then it's also strange as you said that it was triggered later.. as `react-inview-monitor` uses [IntersectionObserver](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) under the hood, and this api doesn't do any internal polling, so... what triggered the update? Did you scroll?

What's your setup when you're noticing this behavior? Is it in dev, running with just client side JS? Or do you have a ~ server rendered html that react bootstraps?

**Comment by pocketjoso** [comment]
Closing due to lack of response - feel free to comment again and I will re-open the issue.
