### ISSUE TITLE
toggleChildPropsOnInView toggles class names

### ISSUE THREAD

**Issue by austinmayer** [snipsco/react-inview-monitor#14]
Using InViewMonitor to trigger component props on a Video player. When `toggleChildPropsOnInView={true}` it toggles classes even when `toggleClassNameOnInView={false}`. It is possible to have both? Toggle childProps, but not css classes?

Usage:
``` javascript
<InViewMonitor
  childPropsInView={{ isPlaying: true }}
  toggleChildPropsOnInView={true}
  toggleClassNameOnInView={false}
  classNameNotInView="animated fadeOut"
  classNameInView="animated fadeIn"
>
    <Video key={item + index} src={item} />
</InViewMonitor>

**Comment by pocketjoso** [comment]
So to clarify, you don't want the class name toggling, so what you would want to use would be:
```js
<InViewMonitor
  childPropsInView={{ isPlaying: true }}
  toggleChildPropsOnInView={true}
  toggleClassNameOnInView={false}
>
    <Video key={item + index} src={item} />
</InViewMonitor>
```
Let me know if that seems right.

I do think this is reasonable, so I'll look into fixing this.

**Comment by austinmayer** [comment]
Thanks for the response!

Correct, no class name toggling. But it would be nice if classes still apply on first InView.

**Comment by pocketjoso** [comment]
Pushed a fix for this bug. It will still apply the clas on first inView - as long as you provide the `classNameInView` prop.
``jsx
<InViewMonitor
  childPropsInView={{ isPlaying: true }}
  toggleChildPropsOnInView={true}
  classNameInView="animated fadeIn"
>
    <Video key={item + index} src={item} />
</InViewMonitor>
```
(`toggleClassNameOnInView` defaults to `false`, so doesn't have to be passed as a prop)

**Comment by pocketjoso** [comment]
> But it would be nice if classes still apply on first InView.

This however is currently not supported in this library.

**Comment by pocketjoso** [comment]
Okay, pushed commits for this too now, published a release candidate version: `react-inview-monitor@2.2.1-rc`.
@austinmayer do you think you could try that one and test that it does what you wanted; before I publish a new `latest` version?

**Comment by austinmayer** [comment]
Alright, we're in business. `react-inview-monitor@2.2.1-rc` looks good, thanks for the rc!

No worries re: the class functionality if it doesn't fit or contradicts this fix. My use case was to have a video fadeIn and start playing, stop playing when out of view while retaining visibility.

**Comment by pocketjoso** [comment]
> No worries re: the class functionality if it doesn't fit or contradicts this fix. My use case was to have a video fadeIn and start playing, stop playing when out of view while retaining visibility.

The release candidate should support exactly this: combination of `classNameInView` and `toggleChildPropsOnInView`. Did you test it?

**Comment by austinmayer** [comment]
Got mixed up in the thread copy edits.

Yes, seeing the proper combination of `classNameInView` and `toggleChildPropsOnInView`

Thanks!

**Comment by pocketjoso** [comment]
> Got mixed up in the thread copy edits.

Understandable. :)

Great that it all works now then, will release the new version.

**Comment by pocketjoso** [comment]
`react-inview-monitor@2.2.1` is out!
