### ISSUE TITLE
Components in plain view when scrolling

### ISSUE THREAD

**Issue by gabinuevo** [snipsco/react-inview-monitor#15]
I'm trying to get some divs to animate into view when they are scrolled into, but currently what is occurring is that the item is in plain view upon loading, and when you scroll into it, it disappears for a split second and then animates back into view. However, I would like for only the latter to occur. For reference, this is how I've configured it thus far:

`<InViewMonitor
classNameNotInView="vis-hidden"
classNameInView="animated fadeInUp">`

I've also attached a video to display the bug in question. You can watch it [here](https://www.youtube.com/watch?v=t9h-TJ2EvN8&feature=youtu.be).

I also imported animate.css into the file. Please let me know if I am doing something wrong or if this is indeed a bug. 

Cheers!

**Comment by pocketjoso** [comment]
Hi, sounds like you don't have a `vis-hidden` class in your CSS, can you check? It's not included neither in this library nor in the animate.css one. We use `visibility: hidden;` for this class in our own styles, for example in [the demo](https://snipsco.github.io/react-inview-monitor/).

**Comment by gabinuevo** [comment]
Yes! That was it. Thank you so much :)

**Comment by gabinuevo** [comment]
Closing this now
