### ISSUE TITLE
elements visible at render, then they hide then run animation?

### ISSUE THREAD

**Issue by balakedev** [snipsco/react-inview-monitor#19]
Really odd. when I refresh the page the divs are visible then they hide themselves. its almost like a flicker. As i scroll down the next div is visible, then it hides itself when its about 20% in the viewport, then shows itself with the right animation. 

Anyone encountered this before?

**Comment by pocketjoso** [comment]
Hi,
How are you calling this library; what props are you sending the component(s) when you are using it?
The `20%` sounds like the default for the `intoViewMargin` prop:
> Margin added to viewport for area to consider “in view”, can be negative. Use f.e. with positive value for lazy loading content just before in view, or with negative to start fading in element just after in view. Must be px or %. Default: ‘-20%’.

Did you read about the different props in the README?

**Comment by balakedev** [comment]
@pocketjoso  Hey mate, yeah fixed it! all good. Love what you've done, its epic.
