### ISSUE TITLE
onInView & onNotInView always triggered?

### ISSUE THREAD

**Issue by DarioSoller** [snipsco/react-inview-monitor#5]
I am struggling to get the callbacks for the `onInView` and `onNotInView` properties working. In the documentation it says, that these properties expect an object as argument, but when I pass in an object the following error occurs:
```
Warning: Failed prop type: Invalid prop 'onNotInView' of type 'object' supplied to 'InviewMonitor', expected 'function'.
    in InviewMonitor (created by ChapterOverview)
    in ChapterOverview (created by Menu)
    in div (created by Menu)
    in div (created by Menu)
    in Menu (created by App)
    in div (created by App)
    in App
    in Router (created by BrowserRouter)
    in BrowserRouter
```
Despite this error, I am not quite sure, to which object property I should assign the callback to (if the documentation is right and I need to use an object and not a function as the property argument).

Here is how I tried it, directly passing in a function callback, which does not throw any errors:
```
<InViewMonitor onInView={this.handleOnInView()} onNotInView={this.handleOnNotInView()} classNameNotInView="in-view-el in-view-hidden" classNameInView="in-view-el in-view">
  <SVGInline svg={chapterOverview1d} className="desktop"/>
  <SVGInline svg={chapterOverview1m} className="mobile"/>
  <Link to="/chapters/1" className="reset c2a-btn" onClick={this.props.closeMenu}><Translate value="chapters.1.title"/></Link>
</InViewMonitor>
```

The example above sets the classes as expected but always triggers both the `onInView`and `onNotInView` at componentDidMount-time, independent of actually being visible in the viewport or not.

Am I missing any point here?
I am relatively new to react, so I am not sure how to quickly provide a working codepen/jsfiddle  example, reproducing this bug. Help appreciated!?

**Comment by pocketjoso** [comment]
Hi,
the documentation was wrong, the type should be `function`, and I have updated this now.

Your example has another error - you should pass the functions themselves, not the output of what the functions return.
Bad (function invocation, will pass what the function returns):
`onInView={this.handleOnInView()}`
Good (passing the function as the prop)
`onInView={this.handleOnInView}`

**Comment by DarioSoller** [comment]
Hi & Thanks for your quick response!
My bad function invocation was the problem. As I haven't returned anything in the callback handler, this caused the unexpected behavior, that `onInView` and `onNotInView`got immediately called. 

So for reference, this worked for me like a charme:
```
<InViewMonitor onInView={this.handleOnInView} onNotInView={this.handleOnNotInView} classNameNotInView="in-view-el in-view-hidden" classNameInView="in-view-el in-view">
    <SVGInline svg={chapterOverview1d} className="desktop"/>
    <SVGInline svg={chapterOverview1m} className="mobile"/>
    <Link to="/chapters/1" className="reset c2a-btn" onClick={this.props.closeMenu}><Translate value="chapters.1.title"/></Link>
  </InViewMonitor>
```

Thanks again!
