### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by AISG-NYC** [snipsco/react-inview-monitor#8]
Tested this in mobile and seems like there is no support for it on mobile? 

Is that right? or maybe there is something I am missing?

**Comment by pocketjoso** [comment]
Hi, this should work just the same on mobile - what exact browser (and OS) are you using?
It might be that your browser requires a polyfill for IntersectionObserver, please see:
https://github.com/snipsco/react-inview-monitor#support

**Comment by AISG-NYC** [comment]
Ah i see.

totally missed that part. I ended up solving my issue with another library
as I needed a quick turnaround.

**Comment by pocketjoso** [comment]
It's super quick to add the polyfill script for IntersectionObserver, in case you want to try again in the future!

**Comment by AISG-NYC** [comment]
i wish i would ve known this at that time

**Comment by pocketjoso** [comment]
That's interesting. What browsers were you trying, on what kind of phone? And what kind of test were you performing?

**Comment by AISG-NYC** [comment]
Tried it on safari and chrome via iPhone. 

Simply tried the onInView func and it would not run at all.

**Comment by AISG-NYC** [comment]
so the demo page shows all elements on the page with no transitions or
fade? is that the expected behavior?

**Comment by pocketjoso** [comment]
No, it sounds like it is not working for you. The video at the bottom never starts playing either?

What version of Safari do you have on your iPhone?

**Comment by AISG-NYC** [comment]
v 11.3.1

No video as well on the demo page!

**Comment by pocketjoso** [comment]
So found a few things:
- this library itself was not broken, however:
- the IntersectionObserver polyfill requires setting `height: 100%` on html+body to work correctly in Safari; this was what the examples missed and why they were not working (animating etc) in Safari.
@AISG-NYC Can you test the examples again and confirm they work for you? This means that you can use this library, but you do need to use the Polyfill, and you need to apply the height change in your css. I'm now mentioning this in the README as well.

Finally, there seems to be a separate problem with the video on in the examples, for some reason it's not showing at all in mobile Safari. I'll debug that separately.

**Comment by AISG-NYC** [comment]
We r in business !!
Thanks for the fix mate!
